/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2023-06-21 10:49:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminData_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1686907102789L));
    _jspx_dependants.put("jar:file:/D:/Documents/struts/EmployeeApprisalApp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/EmployeeApprisalForm/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<div  id=\"afterData\">\r\n");
      out.write("	 	<div>Employee Name : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeDetails.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("	 	<div>Employee CTC : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeDetails.ctc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("	 	<div>Employee Level : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeDetails.level}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("	 	<div>Employee designation : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeDetails.designation}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("	 	<div>Employee email : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeDetails.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("	 	\r\n");
      out.write("	  <label for=\"joiningDate\">Joining Date:</label>\r\n");
      out.write("	  <input type=\"text\" id=\"joiningDate\" name=\"joiningDate\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeDetails.postedDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" disabled />\r\n");
      out.write("	  <label for=\"ProcessedDate\">Processed Date:</label>\r\n");
      out.write("	  <input type=\"text\" id=\"ProcessedDate\" name=\"ProcessedDate\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeDetails.processedDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" disabled />\r\n");
      out.write("	  <br />\r\n");
      out.write("	  <!-- Button to open the modal -->\r\n");
      out.write("	  <h4>Do you want to promote?</h4>\r\n");
      out.write("	  <button id=\"openModalBtn1\">Yes</button>\r\n");
      out.write("	  <button id=\"openModalBtn2\">No</button>\r\n");
      out.write("	\r\n");
      out.write("	  <!-- Modal -->\r\n");
      out.write("	  <div id=\"myModal1\" class=\"modal\">\r\n");
      out.write("	    <div class=\"modal-content\">\r\n");
      out.write("	      <span id=\"close1\" class=\"close\">&times;</span>\r\n");
      out.write("	      <h2>Employee Details</h2>\r\n");
      out.write("	      <form id=\"employeeForm\">\r\n");
      out.write("	        <label for=\"basicSalary\">Current CTC:</label>\r\n");
      out.write("	        <input type=\"text\" id=\"basicSalary\" name=\"basicSalary\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeDetails.ctc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" disabled />\r\n");
      out.write("	\r\n");
      out.write("	        <label for=\"revCTC\">Revised CTC:</label>\r\n");
      out.write("	        <input type=\"text\" id=\"revCTC\" name=\"revCTC\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeDetails.ctc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required />\r\n");
      out.write("	\r\n");
      out.write("	        <label for=\"curLevel\">Current Level:</label>\r\n");
      out.write("	        <input type=\"text\" id=\"curLevel\" name=\"curLevel\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeDetails.level}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" disabled />\r\n");
      out.write("	\r\n");
      out.write("	        <label for=\"level\">Revised Level:</label>\r\n");
      out.write("	        <select id=\"level\" name=\"level\" required>\r\n");
      out.write("		        <option value=\"\">Select Level</option>\r\n");
      out.write("				\r\n");
      out.write("				 ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			\r\n");
      out.write("				\r\n");
      out.write("		          \r\n");
      out.write("	          <!-- Add more options for different levels -->\r\n");
      out.write("	        </select>\r\n");
      out.write("	\r\n");
      out.write("	        <label for=\"designation\">Designation:</label>\r\n");
      out.write("	        <input type=\"text\" id=\"designation\" name=\"designation\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeDetails.designation}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required />\r\n");
      out.write("	\r\n");
      out.write("	        <button style=\"margin:10px 220px;\" onclick=\"updateDatabaseYes()\" >Update</button>\r\n");
      out.write("	      </form>\r\n");
      out.write("	    </div>\r\n");
      out.write("	  </div>\r\n");
      out.write("	\r\n");
      out.write("	  <div id=\"myModal2\" class=\"modal\">\r\n");
      out.write("	    <div class=\"modal-content\">\r\n");
      out.write("	      <span id=\"close2\" class=\"close\">&times;</span>\r\n");
      out.write("	      <h2>Employee Salary Details</h2>\r\n");
      out.write("	      <div class=\"modalpart\">\r\n");
      out.write("	        <h2>Main pay</h2>\r\n");
      out.write("	        <label>\r\n");
      out.write("	          <input type=\"radio\" name=\"section1\" value=\"basic\" onclick=\"enableSection2('basic')\" />\r\n");
      out.write("	          Basic\r\n");
      out.write("	        </label>\r\n");
      out.write("	        <input type=\"text\" id=\"basicSalary2\" name=\"basicSalary2\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeDetails.basic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" disabled />\r\n");
      out.write("	        <span style=\"color: rebeccapurple;\" > <span id=\"basicper\">0</span> % incremented</span>\r\n");
      out.write("	        <br />\r\n");
      out.write("	        <label>\r\n");
      out.write("	          <input type=\"radio\" name=\"section1\" value=\"medical\" onclick=\"enableSection2('medical')\" />\r\n");
      out.write("	          Medical </label><input type=\"text\" id=\"medicalSalary\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeDetails.medical}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" disabled />\r\n");
      out.write("	          <span style=\"color: rebeccapurple;\" > <span id=\"medicalper\">0</span> % incremented</span>\r\n");
      out.write("	          <br />\r\n");
      out.write("	        <label>\r\n");
      out.write("	          <input type=\"radio\" name=\"section1\" value=\"special\" onclick=\"enableSection2('special')\" />\r\n");
      out.write("	          Special Allowance </label><input type=\"text\" id=\"specialSalary\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeDetails.specialAllowances}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" disabled />\r\n");
      out.write("	          <span style=\"color: rebeccapurple;\" > <span id=\"saper\">0</span> % incremented</span>\r\n");
      out.write("	          <br />\r\n");
      out.write("	\r\n");
      out.write("	        <div id=\"sectionIndicator\" style=\"display: none\">\r\n");
      out.write("	          <h2 id=\"sectionNameIndicator\">Section 2</h2>\r\n");
      out.write("	          <form>\r\n");
      out.write("	            <label for=\"percentageSelect\">Percentage:</label>\r\n");
      out.write("	            <select id=\"percentageSelect\" onchange=\"showManualInput()\">\r\n");
      out.write("	              <option value=\"5\">5%</option>\r\n");
      out.write("	              <option value=\"10\">10%</option>\r\n");
      out.write("	              <option value=\"15\">15%</option>\r\n");
      out.write("	              <option value=\"manual\">Manual</option>\r\n");
      out.write("	            </select>\r\n");
      out.write("	            <input type=\"text\" id=\"manualInput\" style=\"display: none\" onchange=\"manualChange()\" />\r\n");
      out.write("	          </form>\r\n");
      out.write("	        </div>\r\n");
      out.write("	      </div>\r\n");
      out.write("	      <div class=\"modalpart\">\r\n");
      out.write("	        <h2>secondary pay</h2>\r\n");
      out.write("	        <div id=\"inputFields\">\r\n");
      out.write("	          <label for=\"pfInput\">\r\n");
      out.write("	            <input name=\"section3\" type=\"radio\" id=\"pfInput\"  onclick=\"enableSection3('pf')\" disabled />PF:</label>\r\n");
      out.write("	            <input type=\"text\" id=\"pfTextInput\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeDetails.pf}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" disabled>\r\n");
      out.write("	          <br />\r\n");
      out.write("	\r\n");
      out.write("	          <label for=\"hraInput\">\r\n");
      out.write("	            <input name=\"section3\" type=\"radio\" id=\"hraInput\" onclick=\"enableSection3('hra')\" disabled />HRA:</label>\r\n");
      out.write("	            <input type=\"text\" id=\"hraTextInput\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeDetails.hra}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" disabled>\r\n");
      out.write("	          <br />\r\n");
      out.write("	\r\n");
      out.write("	          <label for=\"foodInput\">\r\n");
      out.write("	            <input name=\"section3\" type=\"radio\" id=\"foodInput\"  onclick=\"enableSection3('food')\"disabled />Food:</label>\r\n");
      out.write("	            <input type=\"text\" id=\"foodTextInput\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeDetails.food}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" disabled>\r\n");
      out.write("	          <br />\r\n");
      out.write("	\r\n");
      out.write("	          <label for=\"travelInput\">\r\n");
      out.write("	            <input name=\"section3\" type=\"radio\" id=\"travelInput\" onclick=\"enableSection3('travel')\" disabled />Travel:</label>\r\n");
      out.write("	            <input type=\"text\" id=\"travelTextInput\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeDetails.travel}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" disabled>\r\n");
      out.write("	          <br />\r\n");
      out.write("	        </div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	        <div id=\"sectionIndicator2\" style=\"display: none\">\r\n");
      out.write("	          <h2 id=\"sectionNameIndicator2\">Section 4</h2>\r\n");
      out.write("	          <form>\r\n");
      out.write("	            <label for=\"percentageSelect2\">Percentage:</label>\r\n");
      out.write("	            <select id=\"percentageSelect2\" onchange=\"showManualInput2()\" >\r\n");
      out.write("	              <option value=\"5\">5%</option>\r\n");
      out.write("	              <option value=\"10\">10%</option>\r\n");
      out.write("	              <option value=\"15\">15%</option>\r\n");
      out.write("	              <option value=\"manual\">Manual</option>\r\n");
      out.write("	            </select>\r\n");
      out.write("	            <input type=\"text\" id=\"manualInput2\" style=\"display: none\" onchange=\"manualChange2()\" />\r\n");
      out.write("	          </form>\r\n");
      out.write("	        </div>\r\n");
      out.write("	      </div>\r\n");
      out.write("	    	<button style=\"margin:10px 220px;\" onclick=\"updateDatabaseNo()\" >Update</button>\r\n");
      out.write("	    </div>\r\n");
      out.write("	  </div>\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	\r\n");
      out.write("	function updateDatabaseNo(){\r\n");
      out.write("		var data={\r\n");
      out.write("				type:\"no_promotion\",\r\n");
      out.write("				eid:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeDetails.empID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\r\n");
      out.write("				basic:document.getElementById(\"basicSalary2\").value,\r\n");
      out.write("				medical:document.getElementById(\"medicalSalary\").value,\r\n");
      out.write("				sa:document.getElementById(\"specialSalary\").value,\r\n");
      out.write("				hra:document.getElementById(\"hraTextInput\").value,\r\n");
      out.write("				pf:document.getElementById(\"pfTextInput\").value,\r\n");
      out.write("				food:document.getElementById(\"foodTextInput\").value,\r\n");
      out.write("				travel:document.getElementById(\"travelTextInput\").value\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		 $.ajax({\r\n");
      out.write("	    	    url: 'updateDetails.do',\r\n");
      out.write("	    	    type: 'POST',\r\n");
      out.write("	    	    dataType: 'html',\r\n");
      out.write("	    	    data: data,\r\n");
      out.write("	    	    success: function(response) {\r\n");
      out.write("	    	    	 closeModal2();\r\n");
      out.write("	    	    	 alert(\"User's salary is updated\");\r\n");
      out.write("	    	    	 $('#nextContent').html(response);\r\n");
      out.write("	    	    },\r\n");
      out.write("	    	    error: function(xhr, status, error) {\r\n");
      out.write("	    	    	alert(\"User's salary is updated\");\r\n");
      out.write("	    	    }\r\n");
      out.write("	    });\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function updateDatabaseYes(){\r\n");
      out.write("		var data={\r\n");
      out.write("				type:\"yes_promotion\",\r\n");
      out.write("				eid:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeDetails.empID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\r\n");
      out.write("				ctc:document.getElementById(\"revCTC\").value,\r\n");
      out.write("				lvl:document.getElementById(\"level\").value,\r\n");
      out.write("				dsg:document.getElementById(\"designation\").value\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		 $.ajax({\r\n");
      out.write("	    	    url: 'updateDetails.do',\r\n");
      out.write("	    	    type: 'POST',\r\n");
      out.write("	    	    dataType: 'html',\r\n");
      out.write("	    	    data: data,\r\n");
      out.write("	    	    success: function(response) {\r\n");
      out.write("	    	    	 closeModal1();\r\n");
      out.write("	    	    	 alert(\"User's is now promoted\");\r\n");
      out.write("	    	    	 $('#nextContent').html(response);\r\n");
      out.write("	    	    },\r\n");
      out.write("	    	    error: function(xhr, status, error) {\r\n");
      out.write("	    	    	alert(\"Useris not promoted!an error occured\");\r\n");
      out.write("	    	    }\r\n");
      out.write("	    });\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("		\r\n");
      out.write("  <script>\r\n");
      out.write("    // Get the modal element\r\n");
      out.write("    var modal1 = document.getElementById(\"myModal1\");\r\n");
      out.write("\r\n");
      out.write("    // Get the button that opens the modal\r\n");
      out.write("    var openModalBtn1 = document.getElementById(\"openModalBtn1\");\r\n");
      out.write("\r\n");
      out.write("    // Get the close button element\r\n");
      out.write("    var closeBtn1 = document.getElementById(\"close1\");\r\n");
      out.write("\r\n");
      out.write("    // Function to open the modal\r\n");
      out.write("    function openModal1() {\r\n");
      out.write("      modal1.style.display = \"block\";\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Function to close the modal\r\n");
      out.write("    function closeModal1() {\r\n");
      out.write("      modal1.style.display = \"none\";\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    openModalBtn1.addEventListener(\"click\", openModal1);\r\n");
      out.write("\r\n");
      out.write("    // Close the modal when the close button is clicked\r\n");
      out.write("    closeBtn1.addEventListener(\"click\", closeModal1);\r\n");
      out.write("\r\n");
      out.write("    // Close the modal when the user clicks outside the modal content\r\n");
      out.write("    window.addEventListener(\"click\", function (event) {\r\n");
      out.write("      if (event.target == modal1) {\r\n");
      out.write("        closeModal1();\r\n");
      out.write("      }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // Submit form data\r\n");
      out.write("    document\r\n");
      out.write("      .getElementById(\"employeeForm\")\r\n");
      out.write("      .addEventListener(\"submit\", function (event) {\r\n");
      out.write("        event.preventDefault();\r\n");
      out.write("\r\n");
      out.write("        // Retrieve form field values\r\n");
      out.write("        var basicSalary = document.getElementById(\"basicSalary\").value;\r\n");
      out.write("        var level = document.getElementById(\"level\").value;\r\n");
      out.write("        var designation = document.getElementById(\"designation\").value;\r\n");
      out.write("\r\n");
      out.write("        // Perform further actions with the form data (e.g., submit to server)\r\n");
      out.write("        console.log(\"Basic Salary: \" + basicSalary);\r\n");
      out.write("        console.log(\"Level: \" + level);\r\n");
      out.write("        console.log(\"Designation: \" + designation);\r\n");
      out.write("\r\n");
      out.write("        // Close the modal after submitting the form\r\n");
      out.write("        closeModal1();\r\n");
      out.write("      });\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("  <script>\r\n");
      out.write("    // Get the modal element\r\n");
      out.write("    var modal2 = document.getElementById(\"myModal2\");\r\n");
      out.write("\r\n");
      out.write("    // Get the button that opens the modal\r\n");
      out.write("    var openModalBtn2 = document.getElementById(\"openModalBtn2\");\r\n");
      out.write("\r\n");
      out.write("    // Get the close button element\r\n");
      out.write("    var closeBtn2 = document.getElementById(\"close2\");\r\n");
      out.write("	\r\n");
      out.write("    // Function to open the modal\r\n");
      out.write("    function openModal2() {\r\n");
      out.write("      modal2.style.display = \"block\";\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Function to close the modal\r\n");
      out.write("    function closeModal2() {\r\n");
      out.write("      modal2.style.display = \"none\";\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    openModalBtn2.addEventListener(\"click\", openModal2);\r\n");
      out.write("\r\n");
      out.write("    // Close the modal when the close button is clicked\r\n");
      out.write("    closeBtn2.addEventListener(\"click\", closeModal2);\r\n");
      out.write("\r\n");
      out.write("    // Close the modal when the user clicks outside the modal content\r\n");
      out.write("    window.addEventListener(\"click\", function (event) {\r\n");
      out.write("      if (event.target == modal2) {\r\n");
      out.write("        closeModal2();\r\n");
      out.write("      }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // Submit form data\r\n");
      out.write("    document\r\n");
      out.write("      .getElementById(\"employeeForm\")\r\n");
      out.write("      .addEventListener(\"submit\", function (event) {\r\n");
      out.write("        event.preventDefault();\r\n");
      out.write("\r\n");
      out.write("        // Retrieve form field values\r\n");
      out.write("        var basicSalary = document.getElementById(\"basicSalary\").value;\r\n");
      out.write("        var level = document.getElementById(\"level\").value;\r\n");
      out.write("        var designation = document.getElementById(\"designation\").value;\r\n");
      out.write("\r\n");
      out.write("        // Perform further actions with the form data (e.g., submit to server)\r\n");
      out.write("        console.log(\"Basic Salary: \" + basicSalary);\r\n");
      out.write("        console.log(\"Level: \" + level);\r\n");
      out.write("        console.log(\"Designation: \" + designation);\r\n");
      out.write("\r\n");
      out.write("        // Close the modal after submitting the form\r\n");
      out.write("        closeModal2();\r\n");
      out.write("      });\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("  <script>\r\n");
      out.write("    // Get the modal element\r\n");
      out.write("\r\n");
      out.write("    var selectedSection = null;\r\n");
      out.write("    function enableSection2(selection) {\r\n");
      out.write("      var inputFields = document.getElementById(\"inputFields\");\r\n");
      out.write("      document.getElementById(\"sectionIndicator\").style.display = \"block\";\r\n");
      out.write("      var sectionNameIndicator = document.getElementById(\r\n");
      out.write("        \"sectionNameIndicator\"\r\n");
      out.write("      );\r\n");
      out.write("      backToDefault();\r\n");
      out.write("\r\n");
      out.write("      // Enable or disable input fields based on the selection\r\n");
      out.write("      if (selection === \"basic\") {\r\n");
      out.write("        sectionNameIndicator.innerHTML = \"Basic Salary Increment\";\r\n");
      out.write("        selectedSection = \"basic\";\r\n");
      out.write("        console.log(selectedSection);\r\n");
      out.write("        document.getElementById(\"pfInput\").disabled = false;\r\n");
      out.write("        document.getElementById(\"hraInput\").disabled = false;\r\n");
      out.write("        document.getElementById(\"foodInput\").disabled = true;\r\n");
      out.write("        document.getElementById(\"travelInput\").disabled = true;\r\n");
      out.write("      } else if (selection === \"special\") {\r\n");
      out.write("        sectionNameIndicator.innerHTML = \"Special allowence Increment\";\r\n");
      out.write("        selectedSection = \"special\";\r\n");
      out.write("        document.getElementById(\"pfInput\").disabled = true;\r\n");
      out.write("        document.getElementById(\"hraInput\").disabled = true;\r\n");
      out.write("        document.getElementById(\"foodInput\").disabled = false;\r\n");
      out.write("        document.getElementById(\"travelInput\").disabled = false;\r\n");
      out.write("      } else if (selection === \"medical\") {\r\n");
      out.write("        sectionNameIndicator.innerHTML = \"Medical benefit Increment\";\r\n");
      out.write("        selectedSection = \"medical\";\r\n");
      out.write("        document.getElementById(\"pfInput\").disabled = true;\r\n");
      out.write("        document.getElementById(\"hraInput\").disabled = true;\r\n");
      out.write("        document.getElementById(\"foodInput\").disabled = true;\r\n");
      out.write("        document.getElementById(\"travelInput\").disabled = true;\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function showManualInput() {\r\n");
      out.write("      var percentageSelect = document.getElementById(\"percentageSelect\");\r\n");
      out.write("      var manualInput = document.getElementById(\"manualInput\");\r\n");
      out.write("\r\n");
      out.write("      if (percentageSelect.value === \"manual\") {\r\n");
      out.write("        manualInput.style.display = \"inline-block\";\r\n");
      out.write("      } else {\r\n");
      out.write("        manualInput.style.display = \"none\";\r\n");
      out.write("        changeValue(percentageSelect.value);\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function manualChange() {\r\n");
      out.write("      var manualInput = document.getElementById(\"manualInput\");\r\n");
      out.write("      console.log(selectedSection, \"Value: \" + manualInput.value);\r\n");
      out.write("      changeValue(manualInput.value);\r\n");
      out.write("    }\r\n");
      out.write("    function dectwo(number) {\r\n");
      out.write("    	  return Number(number.toFixed(2)).toString();\r\n");
      out.write("    	}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    function changeValue(value) {\r\n");
      out.write("      console.log(selectedSection, \"Value: \" + value);\r\n");
      out.write("      if (selectedSection === \"basic\") {\r\n");
      out.write("        document.getElementById(\"basicSalary2\").value = dectwo(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeDetails.basic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("*(100+Number(value))/100);\r\n");
      out.write("        document.getElementById(\"basicper\").innerHTML=value;\r\n");
      out.write("      } else if (selectedSection === \"medical\") {\r\n");
      out.write("    	  document.getElementById(\"medicalSalary\").value = dectwo(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeDetails.medical}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("*(100+Number(value))/100);\r\n");
      out.write("    	  document.getElementById(\"medicalper\").innerHTML=value;\r\n");
      out.write("        \r\n");
      out.write("      } else if (selectedSection === \"special\") {\r\n");
      out.write("    	  document.getElementById(\"specialSalary\").value = dectwo(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeDetails.specialAllowances}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("*(100+Number(value))/100);\r\n");
      out.write("    	  document.getElementById(\"saper\").innerHTML=value;\r\n");
      out.write("        \r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function backToDefault(){\r\n");
      out.write("      document.getElementById(\"manualInput\").value = \"\";\r\n");
      out.write("      document.getElementById(\"percentageSelect\").value = \"default\";\r\n");
      out.write("      document.getElementById(\"manualInput\").style.display = \"none\";\r\n");
      out.write("    }\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("  <script>\r\n");
      out.write("    // Get the modal element\r\n");
      out.write("\r\n");
      out.write("    var selectedSection2 = null;\r\n");
      out.write("    function enableSection3(selection) {\r\n");
      out.write("      document.getElementById(\"sectionIndicator2\").style.display = \"block\";\r\n");
      out.write("      var sectionNameIndicator = document.getElementById(\r\n");
      out.write("        \"sectionNameIndicator2\"\r\n");
      out.write("      );\r\n");
      out.write("      backToDefault2();\r\n");
      out.write("\r\n");
      out.write("      // Enable or disable input fields based on the selection\r\n");
      out.write("      if (selection === \"pf\") {\r\n");
      out.write("        sectionNameIndicator.innerHTML = \"PF % of basic pay\";\r\n");
      out.write("        selectedSection2 = \"pf\";\r\n");
      out.write("\r\n");
      out.write("      } else if (selection === \"hra\") {\r\n");
      out.write("        sectionNameIndicator.innerHTML = \"HRA % of basic pay\";\r\n");
      out.write("        selectedSection2 = \"hra\";\r\n");
      out.write("\r\n");
      out.write("      } else if (selection === \"food\") {\r\n");
      out.write("        sectionNameIndicator.innerHTML = \"Food % of Special Allowance \";\r\n");
      out.write("        selectedSection2 = \"food\";\r\n");
      out.write("      }else if (selection === \"travel\") {\r\n");
      out.write("        sectionNameIndicator.innerHTML = \"Travel % of Special Allowance \";\r\n");
      out.write("        selectedSection2 = \"travel\";\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function showManualInput2() {\r\n");
      out.write("      var percentageSelect2 = document.getElementById(\"percentageSelect2\");\r\n");
      out.write("      var manualInput2 = document.getElementById(\"manualInput2\");\r\n");
      out.write("\r\n");
      out.write("      if (percentageSelect2.value === \"manual\") {\r\n");
      out.write("        manualInput2.style.display = \"inline-block\";\r\n");
      out.write("      } else {\r\n");
      out.write("        manualInput2.style.display = \"none\";\r\n");
      out.write("        changeValue2(percentageSelect2.value);\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function manualChange2() {\r\n");
      out.write("      var manualInput2 = document.getElementById(\"manualInput2\");\r\n");
      out.write("      console.log(selectedSection2, \"Value: \" + manualInput2.value);\r\n");
      out.write("      changeValue2(manualInput2.value);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function changeValue2(value) {\r\n");
      out.write("      console.log(selectedSection2, \"Value: \" + value);\r\n");
      out.write("      if (selectedSection2 === \"pf\") {\r\n");
      out.write("        document.getElementById(\"pfTextInput\").value = value;\r\n");
      out.write("      } else if (selectedSection2 === \"hra\") {\r\n");
      out.write("        document.getElementById(\"hraTextInput\").value = value;\r\n");
      out.write("      }else if (selectedSection2 === \"food\") {\r\n");
      out.write("        document.getElementById(\"foodTextInput\").value = value;\r\n");
      out.write("      }else if (selectedSection2 === \"travel\") {\r\n");
      out.write("        document.getElementById(\"travelTextInput\").value = value;\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function backToDefault2(){\r\n");
      out.write("      document.getElementById(\"manualInput2\").value = \"\";\r\n");
      out.write("      document.getElementById(\"percentageSelect2\").value = \"default\";\r\n");
      out.write("      document.getElementById(\"manualInput2\").style.display = \"none\";\r\n");
      out.write("    }\r\n");
      out.write("  </script>\r\n");
      out.write("   \r\n");
      out.write("  <!-- JavaScript code to handle modal functionality -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/adminData.jsp(38,5) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setBegin(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Math.min(employeeDetails.level.substring(1)+1,9)}", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
      // /WEB-INF/views/adminData.jsp(38,5) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setEnd(9);
      // /WEB-INF/views/adminData.jsp(38,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("level");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("				    <option value=\"L");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${level}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write('L');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${level}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("				");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
